name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  COMPONENT_DIR: power_max_tracker

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Update manifest.json version to ${{ github.event.release.tag_name }}
        run: |
          python3 ${{ github.workspace }}/.github/scripts/update_hacs_manifest.py --version ${{ github.event.release.tag_name }} --path /custom_components/power_max_tracker/
      - name: Commit manifest update
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./custom_components/power_max_tracker/manifest.json ./custom_components/power_max_tracker/const.py
          git commit -m "Update for new version ${{ github.event.release.tag_name }}"
          git push origin HEAD:main
      - name: Create zip
        run: |
          cd custom_components/power_max_tracker
          zip power_max_tracker.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/power_max_tracker/power_max_tracker.zip
          asset_name: power_max_tracker.zip
          tag: ${{ github.ref }}
          overwrite: true
